-------------------------------------------------------------------------------
Test set: com.datastax.workshop.TodobackendSpringdataApplicationTests
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 8.788 s <<< FAILURE! - in com.datastax.workshop.TodobackendSpringdataApplicationTests
shoud_save_task_when_save  Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'todoRepositorySimpleCassandra' defined in file [/Volumes/payment/workshop-spring-data-cassandra/todobackend-springdata/target/classes/com/datastax/workshop/todo/TodoRepositorySimpleCassandra.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cassandraSession' defined in class path resource [org/springframework/boot/autoconfigure/cassandra/CassandraAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.datastax.oss.driver.api.core.CqlSession]: Factory method 'cassandraSession' threw exception; nested exception is com.datastax.oss.driver.api.core.AllNodesFailedException: Could not reach any contact point, make sure you've provided valid addresses (showing first 3 nodes, use getAllErrors() for more): Node(endPoint=2dbac318-0292-4124-96aa-f9f609824cc7-europe-west1.db.astra.datastax.com:29042:dd02896e-3950-4246-bd2f-44a52c79370b, hostId=null, hashCode=1380177a): [com.datastax.oss.driver.api.core.auth.AuthenticationException: Authentication error on node 2dbac318-0292-4124-96aa-f9f609824cc7-europe-west1.db.astra.datastax.com:29042:dd02896e-3950-4246-bd2f-44a52c79370b: server replied with 'We recently improved your database security. To find out more and reconnect, see https://docs.datastax.com/en/astra/docs/manage-application-tokens.html' to AuthResponse request], Node(endPoint=2dbac318-0292-4124-96aa-f9f609824cc7-europe-west1.db.astra.datastax.com:29042:c0e15c8c-ffa3-4865-9141-9e6426a6c599, hostId=null, hashCode=20f70c22): [com.datastax.oss.driver.api.core.auth.AuthenticationException: Authentication error on node 2dbac318-0292-4124-96aa-f9f609824cc7-europe-west1.db.astra.datastax.com:29042:c0e15c8c-ffa3-4865-9141-9e6426a6c599: server replied with 'We recently improved your database security. To find out more and reconnect, see https://docs.datastax.com/en/astra/docs/manage-application-tokens.html' to AuthResponse request], Node(endPoint=2dbac318-0292-4124-96aa-f9f609824cc7-europe-west1.db.astra.datastax.com:29042:29470b99-9882-4d26-8bc7-ad8e9ac17e30, hostId=null, hashCode=5bb296e3): [com.datastax.oss.driver.api.core.auth.AuthenticationException: Authentication error on node 2dbac318-0292-4124-96aa-f9f609824cc7-europe-west1.db.astra.datastax.com:29042:29470b99-9882-4d26-8bc7-ad8e9ac17e30: server replied with 'We recently improved your database security. To find out more and reconnect, see https://docs.datastax.com/en/astra/docs/manage-application-tokens.html' to AuthResponse request]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cassandraSession' defined in class path resource [org/springframework/boot/autoconfigure/cassandra/CassandraAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.datastax.oss.driver.api.core.CqlSession]: Factory method 'cassandraSession' threw exception; nested exception is com.datastax.oss.driver.api.core.AllNodesFailedException: Could not reach any contact point, make sure you've provided valid addresses (showing first 3 nodes, use getAllErrors() for more): Node(endPoint=2dbac318-0292-4124-96aa-f9f609824cc7-europe-west1.db.astra.datastax.com:29042:dd02896e-3950-4246-bd2f-44a52c79370b, hostId=null, hashCode=1380177a): [com.datastax.oss.driver.api.core.auth.AuthenticationException: Authentication error on node 2dbac318-0292-4124-96aa-f9f609824cc7-europe-west1.db.astra.datastax.com:29042:dd02896e-3950-4246-bd2f-44a52c79370b: server replied with 'We recently improved your database security. To find out more and reconnect, see https://docs.datastax.com/en/astra/docs/manage-application-tokens.html' to AuthResponse request], Node(endPoint=2dbac318-0292-4124-96aa-f9f609824cc7-europe-west1.db.astra.datastax.com:29042:c0e15c8c-ffa3-4865-9141-9e6426a6c599, hostId=null, hashCode=20f70c22): [com.datastax.oss.driver.api.core.auth.AuthenticationException: Authentication error on node 2dbac318-0292-4124-96aa-f9f609824cc7-europe-west1.db.astra.datastax.com:29042:c0e15c8c-ffa3-4865-9141-9e6426a6c599: server replied with 'We recently improved your database security. To find out more and reconnect, see https://docs.datastax.com/en/astra/docs/manage-application-tokens.html' to AuthResponse request], Node(endPoint=2dbac318-0292-4124-96aa-f9f609824cc7-europe-west1.db.astra.datastax.com:29042:29470b99-9882-4d26-8bc7-ad8e9ac17e30, hostId=null, hashCode=5bb296e3): [com.datastax.oss.driver.api.core.auth.AuthenticationException: Authentication error on node 2dbac318-0292-4124-96aa-f9f609824cc7-europe-west1.db.astra.datastax.com:29042:29470b99-9882-4d26-8bc7-ad8e9ac17e30: server replied with 'We recently improved your database security. To find out more and reconnect, see https://docs.datastax.com/en/astra/docs/manage-application-tokens.html' to AuthResponse request]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.datastax.oss.driver.api.core.CqlSession]: Factory method 'cassandraSession' threw exception; nested exception is com.datastax.oss.driver.api.core.AllNodesFailedException: Could not reach any contact point, make sure you've provided valid addresses (showing first 3 nodes, use getAllErrors() for more): Node(endPoint=2dbac318-0292-4124-96aa-f9f609824cc7-europe-west1.db.astra.datastax.com:29042:dd02896e-3950-4246-bd2f-44a52c79370b, hostId=null, hashCode=1380177a): [com.datastax.oss.driver.api.core.auth.AuthenticationException: Authentication error on node 2dbac318-0292-4124-96aa-f9f609824cc7-europe-west1.db.astra.datastax.com:29042:dd02896e-3950-4246-bd2f-44a52c79370b: server replied with 'We recently improved your database security. To find out more and reconnect, see https://docs.datastax.com/en/astra/docs/manage-application-tokens.html' to AuthResponse request], Node(endPoint=2dbac318-0292-4124-96aa-f9f609824cc7-europe-west1.db.astra.datastax.com:29042:c0e15c8c-ffa3-4865-9141-9e6426a6c599, hostId=null, hashCode=20f70c22): [com.datastax.oss.driver.api.core.auth.AuthenticationException: Authentication error on node 2dbac318-0292-4124-96aa-f9f609824cc7-europe-west1.db.astra.datastax.com:29042:c0e15c8c-ffa3-4865-9141-9e6426a6c599: server replied with 'We recently improved your database security. To find out more and reconnect, see https://docs.datastax.com/en/astra/docs/manage-application-tokens.html' to AuthResponse request], Node(endPoint=2dbac318-0292-4124-96aa-f9f609824cc7-europe-west1.db.astra.datastax.com:29042:29470b99-9882-4d26-8bc7-ad8e9ac17e30, hostId=null, hashCode=5bb296e3): [com.datastax.oss.driver.api.core.auth.AuthenticationException: Authentication error on node 2dbac318-0292-4124-96aa-f9f609824cc7-europe-west1.db.astra.datastax.com:29042:29470b99-9882-4d26-8bc7-ad8e9ac17e30: server replied with 'We recently improved your database security. To find out more and reconnect, see https://docs.datastax.com/en/astra/docs/manage-application-tokens.html' to AuthResponse request]
Caused by: com.datastax.oss.driver.api.core.AllNodesFailedException: Could not reach any contact point, make sure you've provided valid addresses (showing first 3 nodes, use getAllErrors() for more): Node(endPoint=2dbac318-0292-4124-96aa-f9f609824cc7-europe-west1.db.astra.datastax.com:29042:dd02896e-3950-4246-bd2f-44a52c79370b, hostId=null, hashCode=1380177a): [com.datastax.oss.driver.api.core.auth.AuthenticationException: Authentication error on node 2dbac318-0292-4124-96aa-f9f609824cc7-europe-west1.db.astra.datastax.com:29042:dd02896e-3950-4246-bd2f-44a52c79370b: server replied with 'We recently improved your database security. To find out more and reconnect, see https://docs.datastax.com/en/astra/docs/manage-application-tokens.html' to AuthResponse request], Node(endPoint=2dbac318-0292-4124-96aa-f9f609824cc7-europe-west1.db.astra.datastax.com:29042:c0e15c8c-ffa3-4865-9141-9e6426a6c599, hostId=null, hashCode=20f70c22): [com.datastax.oss.driver.api.core.auth.AuthenticationException: Authentication error on node 2dbac318-0292-4124-96aa-f9f609824cc7-europe-west1.db.astra.datastax.com:29042:c0e15c8c-ffa3-4865-9141-9e6426a6c599: server replied with 'We recently improved your database security. To find out more and reconnect, see https://docs.datastax.com/en/astra/docs/manage-application-tokens.html' to AuthResponse request], Node(endPoint=2dbac318-0292-4124-96aa-f9f609824cc7-europe-west1.db.astra.datastax.com:29042:29470b99-9882-4d26-8bc7-ad8e9ac17e30, hostId=null, hashCode=5bb296e3): [com.datastax.oss.driver.api.core.auth.AuthenticationException: Authentication error on node 2dbac318-0292-4124-96aa-f9f609824cc7-europe-west1.db.astra.datastax.com:29042:29470b99-9882-4d26-8bc7-ad8e9ac17e30: server replied with 'We recently improved your database security. To find out more and reconnect, see https://docs.datastax.com/en/astra/docs/manage-application-tokens.html' to AuthResponse request]

